version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ustar_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ustar
      MYSQL_USER: user
      MYSQL_PASSWORD: Green123!@#
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-pGreen123!@#"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  app:
    image: ${DOCKER_IMAGE}
    container_name: ustar_app
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: ${APPLICATION_NAME}
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "10"
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "5"
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: "30000"
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: "1800000"
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: "20000"
      JWT_ACCESS_TOKEN_VALIDITY: ${JWT_ACCESS_TOKEN_VALIDITY}
      JWT_REFRESH_TOKEN_VALIDITY: ${JWT_REFRESH_TOKEN_VALIDITY}
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  mysql_data:
    name: ustar_mysql_data